#!/usr/bin/python3
from sys import argv
import math
from factor import factor

def factors(filename):
    with open(filename, encoding="utf-8") as my_file:
        for i in my_file.readlines():
            n = int(i)
            result = factor(n)

if __name__ == "__main__":
    factors(argv[1])
